name: gods_eye
description: God’s Eye is used to collect data from your testers before release or your actual users after release. This package is used to implement God's Eye.
version: 0.0.1+2
homepage: https://github.com/ajith-m-doodlebug/gods-eye

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  device_info: ^2.0.2
  geolocator: ^7.2.0+1
  http: ^0.13.3
  time: ^2.0.0
  workmanager: ^0.4.1
  shared_preferences: ^2.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

